#!/usr/bin/perl
#
# requires:	gpg
# input:	a text file
# output:	-
# signs the file in place, overwriting the file
#
use strict;
use warnings;

die "error: file param missing\n" if @ARGV<1;
die "error: file '$ARGV[0]' does not exist\n" unless -e $ARGV[0];
my @crypted = `gpg --clearsign --output - $ARGV[0]`;
open(my $outfile, ">", $ARGV[0])
	or die "cannot write $ARGV[0]: $!";
	print $outfile @crypted;
close($outfile);
